version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: psmp
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      PACKWIZ_URL: "https://pirayapartyproviders.github.io/psmp/pack/pack.toml"
      OVERRIDE_SERVER_PROPERTIES: "true"
      OVERRIDE_ICON: "TRUE"
      ICON: "https://pirayapartyproviders.github.io/psmp/piraya.png"
      TYPE: "FABRIC"
      SERVER_NAME: "Piraya SMP"
      MOTD: "§1§cPiraya§r §nSMP"
      DIFFICULTY: "hard"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data