name = "psmp"
author = "Ernst Fisk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b04093fb369a9661c9b952b91759e9284d1ef177016958a5e96031b6efff900c"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
