name = "BigMods"
author = "Oscar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "327521824d9702f8bc97e3eb33943a90d3a759f973d785ac28fa1ecb14aaa847"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.27"
