name = "BigFabric"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f26863ffa036fa86692452ebe978c2000afae8cb8fbd2015bdb973bee3b97ce6"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
