name = "BigFabric"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d8987fcab9af954fbdb4576a382dff4bcabc113206a41568c7ffabc7dc258ae"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
