name = "BigFabric"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96da5b76cbaa9ef413279a94aba682fe13472730103ada54d0eb486e924d3a10"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
