name = "BigFabric"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb045f26d1cbdc558ca7144b61fef556c9c312cfb69ee9aa64ecf840956df4bd"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
