name = "BigFabric"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cce7b285ccb95d95933f115611e51ef52a6a0e13f91e5137e85ee64f070e5cb0"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
