name = "psmp"
author = "Ernst Fisk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a95fa8bb4da14c49a870bc1fba2ffbc34099ddb0c5e12ffed0bf4ec49321d4e"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
