name = "BigMods"
author = "Oscar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35e62d2700822ac6b3c24d70326e5816131638a8eb0357af5bf90652c70d0f1b"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.27"
