name = "BigFabric"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97fb5b68625465dc2102414c67587c7d54ff36b977ff5df2681d64d82b623685"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
