name = "BigFabric"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb128dc848812aa60f5bdc4a97e552c618b5295f311ca1f17d9e050b831c3577"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
