name = "BigFabric"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb03f880350761bf0fab644739e8d59f80d3225c1cc68bad24ad90d481b448ff"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
